### ISSUE TITLE
Ensure all test are passing in github action

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-relayer#15]
https://github.com/open-dollar/od-relayer/actions/runs/7278216524/job/19831929757

> Encountered 1 failing test in test/e2e/SystemOracle.s.sol:OracleSetup
[FAIL. Reason: setup failed: invalid rpc url: ] setUp() (gas: 0)

**Comment by jahabeebs** [comment]
@pi0neerpat Could you please add ARB_MAINNET_RPC and ARB_SEPOLIA_RPC as environment variables to the same values set in the contracts repo so I can test re-running the action?

**Comment by jahabeebs** [comment]
@pi0neerpat I did testing locally and verified that it was an RPC error--when I use infura RPCs instead of quicknode ones all the tests pass successfully. I don't have access to our team's Infura environment so would you mind changing the env variables in this repo to the following:

ARB_MAINNET_RPC=https://arbitrum-mainnet.infura.io/v3/PRIVATE_KEY_HERE
ARB_SEPOLIA_RPC=https://arbitrum-sepolia.infura.io/v3/PRIVATE_KEY_HERE

Thanks!
